repos:
  - repo: local
    hooks:
      - id: cargo fmt
        name: cargo fmt
        entry: cargo fmt
        language: rust
        pass_filenames: false
      - id: cargo check
        name: cargo check
        entry: cargo check
        language: rust
        pass_filenames: false
      - id: cargo clippy
        name: cargo clippy
        entry: cargo clippy
        language: rust
        pass_filenames: false
      - id: cargo test
        name: cargo test
        entry: cargo test
        language: rust
        pass_filenames: false
